baseURL = "https://thanhhv.github.io/"
languageCode = "en-us"
title = "Thanh HV's Blog"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Hi, I'm Thanh HV 👋", Content = "Welcome to my dev blog - sharing backend insights, performance tips, and useful notes." }
  showReadingTime = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  defaultTheme = "light"
  socialIcons = [
    { name = "github", url = "https://github.com/thanhhv" },
    { name = "linkedin", url = "https://www.linkedin.com/in/thanhhv317" },
    { name = "telegram", url = "https://t.me/thanhhv98" }
  ]
[params.utterances]
  repo = "thanhhv/blog-comments"      
  issueTerm = "pathname"           
  label = "💬 comment"                
  theme = "github-light" 
  crossorigin = "anonymous"